sequencescape_url: http://psd-production.internal.sanger.ac.uk:6700
user_agent_for_sequencescape: "Clusterview (production)"
timeout_to_sequencescape: 60

ldap_configuration:
  host: 'ldap.internal.sanger.ac.uk'
  port: '636'
  encryption: :simple_tls

legacy_clusterview_image_path: '/nfs/disk54/badger/sybrgreenqc/uploads'
