sequencescape_url: http://psd-production.internal.sanger.ac.uk:6700

ldap_configuration:
  host: 'ldap.internal.sanger.ac.uk'
  port: '636'
  encryption: :simple_tls

legacy_clusterview_image_path: '/psg/webapps/staging/clusterview/shared/uploads/'
